### ISSUE TITLE
Bug: Automuting someone not in the server throws an error

### ISSUE THREAD

**Issue by Erisa** [Erisa/Cliptok#112]
![image](https://user-images.githubusercontent.com/14004943/142749710-d1363ec0-471f-4c96-9e61-33d93f1f205e.png)
https://discord.com/channels/150662382874525696/187649467611086849/911833106611335198

```
bot_1         | [2021-11-21 04:19:13 +00:00] [1000/Cliptok     ] [Error] Exception occurred during Erisa's invocation of 'warn'
bot_1         | DSharpPlus.Exceptions.NotFoundException: Not found: 404
bot_1         |    at DSharpPlus.Net.DiscordApiClient.GetGuildMemberAsync(UInt64 guild_id, UInt64 user_id)
bot_1         |    at DSharpPlus.Entities.DiscordGuild.GetMemberAsync(UInt64 userId)
bot_1         |    at Cliptok.Modules.Warnings.GiveWarningAsync(DiscordUser targetUser, DiscordUser modUser, String reason, String contextLink, DiscordChannel channel, String extraWord) in /app/Warnings.cs:line 276
bot_1         |    at Cliptok.Modules.Warnings.WarnCmd(CommandContext ctx, DiscordUser targetUser, String reason) in /app/Warnings.cs:line 460
bot_1         |    at DSharpPlus.CommandsNext.Command.ExecuteAsync(CommandContext ctx)
```

**Comment by Erisa** [comment]
Weirdly this doesn't happen for manual mutes, only automatic ones

**Comment by Erisa** [comment]
Ah, pretty sure I've found it 
https://github.com/Erisa/Cliptok/blob/272ca9f807acf1ddfd4b348865449b4d842a51af/Modules/Warnings.cs#L268-L273

Pretty sure the mute accepts users not members, so no idea why member objects are blindly created there. Will have to test and fix tomorrow.
