### ISSUE TITLE
Bug: Tracking add didn't work

### ISSUE THREAD

**Issue by Erisa** [Erisa/Cliptok#214]
<img width="396" alt="image" src="https://github.com/user-attachments/assets/e9e3af5d-686e-4094-8eb7-eb1d9ffca31f">
<img width="358" alt="image" src="https://github.com/user-attachments/assets/2272b5d3-4db6-4476-bb83-b60a85dd96d9">

https://discord.com/channels/150662382874525696/1265358432597315685/1265673136351744041
https://modmail.msft.chat/logs/34f6a0bf5a7d

**Comment by Erisa** [comment]
Restart fixed it, related to bad state in log channel helper
```
[2024-07-24 14:13:36 +00:00] [Error] Error during invocation of interaction command "tracking" by "erisachu"
System.Collections.Generic.KeyNotFoundException: The given key 'investigations' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Cliptok.Commands.InteractionCommands.TrackingInteractions.PermadehoistSlashCommands.TrackingAddSlashCmd(InteractionContext ctx, DiscordUser discordUser) in /app/Commands/InteractionCommands/TrackingInteractions.cs:line 32
   at DSharpPlus.SlashCommands.SlashCommandsExtension.RunCommandAsync(BaseContext context, MethodInfo method, IEnumerable`1 args)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass49_0.<<InteractionHandler>b__0>d.MoveNext()
```
